// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/papyrus/platform/internal/config"
	"github.com/papyrus/platform/internal/infrastructure/httpserver"
	"github.com/papyrus/platform/internal/infrastructure/postgres"
	redis2 "github.com/papyrus/platform/internal/infrastructure/redis"
	"github.com/redis/go-redis/v9"
	"net/http"
)

// Injectors from wire.go:

// InitializeApp builds the full application graph.
func InitializeApp(ctx context.Context, cfg config.Config) (*App, error) {
	pool, err := provideDB(ctx, cfg)
	if err != nil {
		return nil, err
	}
	client, err := provideRedis(ctx, cfg)
	if err != nil {
		return nil, err
	}
	server := provideServer(cfg)
	app := &App{
		Config: cfg,
		DB:     pool,
		Redis:  client,
		Server: server,
	}
	return app, nil
}

// wire.go:

// App holds the wired application dependencies.
type App struct {
	Config config.Config
	DB     *pgxpool.Pool
	Redis  *redis.Client
	Server *http.Server
}

func provideDB(ctx context.Context, cfg config.Config) (*pgxpool.Pool, error) {
	return postgres.Connect(ctx, cfg.DB.DSN())
}

func provideRedis(ctx context.Context, cfg config.Config) (*redis.Client, error) {
	return redis2.Connect(ctx, cfg.Redis.Addr())
}

func provideServer(cfg config.Config) *http.Server {
	return httpserver.NewServer(":"+cfg.Port, httpserver.NewRouter())
}
