// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/jackc/pgx/v5/pgxpool"
	identity2 "github.com/papyrus/platform/internal/application/identity"
	"github.com/papyrus/platform/internal/config"
	"github.com/papyrus/platform/internal/domain/identity"
	"github.com/papyrus/platform/internal/infrastructure/httpserver"
	"github.com/papyrus/platform/internal/infrastructure/hydra"
	"github.com/papyrus/platform/internal/infrastructure/mail"
	"github.com/papyrus/platform/internal/infrastructure/postgres"
	redis2 "github.com/papyrus/platform/internal/infrastructure/redis"
	"github.com/papyrus/platform/internal/infrastructure/security"
	http2 "github.com/papyrus/platform/internal/presentation/http"
	"github.com/redis/go-redis/v9"
	"log"
	"net/http"
	"os"
)

// Injectors from wire.go:

// InitializeApp builds the full application graph.
func InitializeApp(ctx context.Context, cfg config.Config) (*App, error) {
	pool, err := provideDB(ctx, cfg)
	if err != nil {
		return nil, err
	}
	client, err := provideRedis(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := provideUserRepo(pool)
	passwordHasher := provideHasher()
	verificationTokens := provideTokens(client)
	mailer := provideMailer(cfg)
	identityHandlers := provideIdentityHandlers(cfg, userRepository, passwordHasher, verificationTokens, mailer)
	hydraClient := provideHydraClient(cfg)
	sessionRepository := provideSessionRepo(pool)
	authHandlers := provideAuthHandlers(userRepository, passwordHasher, hydraClient, sessionRepository)
	server := provideServer(cfg, identityHandlers, authHandlers)
	app := &App{
		Config: cfg,
		DB:     pool,
		Redis:  client,
		Server: server,
	}
	return app, nil
}

// wire.go:

// App holds the wired application dependencies.
type App struct {
	Config config.Config
	DB     *pgxpool.Pool
	Redis  *redis.Client
	Server *http.Server
}

func provideDB(ctx context.Context, cfg config.Config) (*pgxpool.Pool, error) {
	return postgres.Connect(ctx, cfg.DB.DSN())
}

func provideRedis(ctx context.Context, cfg config.Config) (*redis.Client, error) {
	return redis2.Connect(ctx, cfg.Redis.Addr())
}

func provideUserRepo(pool *pgxpool.Pool) identity.UserRepository {
	return postgres.NewUserRepository(pool)
}

func provideTokens(client *redis.Client) identity.VerificationTokens {
	return redis2.NewTokenStore(client)
}

func provideHasher() identity.PasswordHasher {
	return security.NewBcryptHasher(0)
}

func provideMailer(cfg config.Config) identity.Mailer {
	if cfg.Mail.Mode == "smtp" {
		return mail.NewSMTPMailer(cfg.Mail.Host, cfg.Mail.Port, cfg.Mail.User, cfg.Mail.Password, cfg.Mail.From)
	}
	return mail.NewLogMailer(log.New(os.Stdout, "", log.LstdFlags))
}

func provideIdentityHandlers(cfg config.Config, users identity.UserRepository,
	hasher identity.PasswordHasher, tokens identity.VerificationTokens,
	mailer identity.Mailer) *http2.IdentityHandlers {
	return http2.NewIdentityHandlers(identity2.NewRegisterUser(users, hasher, tokens, mailer, cfg.BaseURL), identity2.NewVerifyEmail(users, tokens), identity2.NewRequestPasswordReset(users, tokens, mailer, cfg.BaseURL), identity2.NewResetPassword(users, hasher, tokens))
}

func provideSessionRepo(pool *pgxpool.Pool) identity.SessionRepository {
	return postgres.NewSessionRepository(pool)
}

func provideHydraClient(cfg config.Config) identity.HydraClient {
	return hydra.New(cfg.Hydra.AdminURL, cfg.TrustedClientIDs)
}

func provideAuthHandlers(users identity.UserRepository, hasher identity.PasswordHasher,
	hydraClient identity.HydraClient, sessions identity.SessionRepository) *http2.AuthHandlers {
	return http2.NewAuthHandlers(identity2.NewAuthenticate(users, hasher), hydraClient, sessions, http2.MustLoadTemplates())
}

func provideServer(cfg config.Config, identity3 *http2.IdentityHandlers, auth *http2.AuthHandlers) *http.Server {
	return httpserver.NewServer(":"+cfg.Port, httpserver.NewRouter(identity3, auth))
}
